import Foundation

extension FeedSource {
    static let defaults: [FeedSource] = [
        // === 総合・ニュース ===
        FeedSource(name: "痛いニュース", feedURL: URL(string: "https://itainews.com/index.rdf")!),
        FeedSource(name: "ハムスター速報", feedURL: URL(string: "https://hamusoku.com/index.rdf")!),
        FeedSource(name: "アルファルファモザイク", feedURL: URL(string: "https://alfalfalfa.com/index.rdf")!),
        FeedSource(name: "暇人速報", feedURL: URL(string: "http://himasoku.com/index.rdf")!),
        FeedSource(name: "哲学ニュースnwk", feedURL: URL(string: "http://blog.livedoor.jp/nwknews/index.rdf")!),
        FeedSource(name: "キニ速", feedURL: URL(string: "http://blog.livedoor.jp/kinisoku/index.rdf")!),
        FeedSource(name: "ニュース30over", feedURL: URL(string: "http://www.news30over.com/index.rdf")!),
        FeedSource(name: "まとめたニュース", feedURL: URL(string: "http://matometanews.com/index.rdf")!),
        FeedSource(name: "カナ速", feedURL: URL(string: "http://kanasoku.info/index.rdf")!),
        FeedSource(name: "ニュー速クオリティ", feedURL: URL(string: "http://news4vip.livedoor.biz/index.rdf")!),
        FeedSource(name: "NEWSOKU BLOG", feedURL: URL(string: "https://newsoku.blog/feed")!),
        FeedSource(name: "ゴールデンタイムズ", feedURL: URL(string: "http://blog.livedoor.jp/goldennews/index.rdf")!),
        FeedSource(name: "億ったー", feedURL: URL(string: "https://okutta.blog.jp/index.rdf")!),
        FeedSource(name: "ガハろぐ", feedURL: URL(string: "http://gahalog.2chblog.jp/index.rdf")!),
        FeedSource(name: "2chコピペ保存道場", feedURL: URL(string: "http://2chcopipe.com/index.rdf")!),
        FeedSource(name: "ワロタニッキ", feedURL: URL(string: "http://warotanikki.com/index.rdf")!),
        FeedSource(name: "不思議.net", feedURL: URL(string: "https://world-fusigi.net/index.rdf")!),
        FeedSource(name: "BIPブログ", feedURL: URL(string: "http://bipblog.com/index.rdf")!),
        FeedSource(name: "ぶる速", feedURL: URL(string: "http://burusoku-vip.com/index.rdf")!),
        FeedSource(name: "VIPワイドガイド", feedURL: URL(string: "http://news4wide.livedoor.biz/index.rdf")!),
        FeedSource(name: "暇つぶしニュース", feedURL: URL(string: "http://blog.livedoor.jp/rbkyn844/index.rdf")!),
        FeedSource(name: "カオスちゃんねる", feedURL: URL(string: "http://chaos2ch.com/index.rdf")!),
        FeedSource(name: "NEWSまとめもりー", feedURL: URL(string: "http://www.akb48matomemory.com/index.rdf")!),
        FeedSource(name: "おーるじゃんる", feedURL: URL(string: "http://crx7601.com/index.rdf")!),
        FeedSource(name: "ラビット速報", feedURL: URL(string: "http://rabbitsokuhou.blog.jp/index.rdf")!),
        FeedSource(name: "ヒロイモノ中毒", feedURL: URL(string: "http://cherio199.blog120.fc2.com/?xml")!),
        FeedSource(name: "ぷちそく！！", feedURL: URL(string: "http://petitsoku.blog.jp/index.rdf")!),
        FeedSource(name: "やみ速", feedURL: URL(string: "https://yamisoku.blog.jp/index.rdf")!),
        FeedSource(name: "じわるチャンネル", feedURL: URL(string: "https://jiwaru-channel.com/feed")!),
        FeedSource(name: "ヤバイ！ニュース", feedURL: URL(string: "https://yabai-news.blog.jp/index.rdf")!),
        FeedSource(name: "まんぷくにゅーす", feedURL: URL(string: "http://manpuku-news.blog.jp/index.rdf")!),
        FeedSource(name: "ひろぶろ", feedURL: URL(string: "http://www.hiroburo.com/index.rdf")!),
        FeedSource(name: "さまざま日報", feedURL: URL(string: "https://samazamanippo.blog.jp/index.rdf")!),
        FeedSource(name: "2chNEWSまとめ", feedURL: URL(string: "https://2ch-news-matome.blog.jp/index.rdf")!),
        FeedSource(name: "あのころの", feedURL: URL(string: "http://anokorono.blog.jp/index.rdf")!),
        FeedSource(name: "理想ちゃんねる", feedURL: URL(string: "https://risou-channel.blog.jp/index.rdf")!),
        FeedSource(name: "じわ速", feedURL: URL(string: "https://jiwasoku.blog.jp/index.rdf")!),
        FeedSource(name: "ゴシップ速報", feedURL: URL(string: "http://gossip1.net/index.rdf")!),
        FeedSource(name: "NEWSぽけまとめーる", feedURL: URL(string: "https://newspoke.blog.jp/index.rdf")!),
        FeedSource(name: "トレンドの通り道", feedURL: URL(string: "https://trend-torimichi.blog.jp/index.rdf")!),
        FeedSource(name: "なんでもいいよちゃんねるNEO", feedURL: URL(string: "https://nandemoyoich-neo.blog.jp/index.rdf")!),
        FeedSource(name: "時事ネタニュース速報", feedURL: URL(string: "https://jijineta-news.blog.jp/index.rdf")!),
        FeedSource(name: "大艦巨砲主義！", feedURL: URL(string: "http://military38.com/index.rdf")!),
        FeedSource(name: "U-1 NEWS", feedURL: URL(string: "https://you1news.com/feed")!),
        FeedSource(name: "国家総動員報", feedURL: URL(string: "https://totalwar.doorblog.jp/index.rdf")!),
        FeedSource(name: "あじあのネタ帳", feedURL: URL(string: "http://asianews2ch.jp/index.rdf")!),
        FeedSource(name: "貧乏暇なり", feedURL: URL(string: "https://binbohima.blog.jp/index.rdf")!),
        FeedSource(name: "日本第一！ニュース録", feedURL: URL(string: "https://incident-wo.com/feed")!),

        // === VIP・なんJ ===
        FeedSource(name: "VIPPERな俺", feedURL: URL(string: "http://blog.livedoor.jp/news23vip/index.rdf")!),
        FeedSource(name: "VIPPER速報", feedURL: URL(string: "http://vippers.jp/index.rdf")!),
        FeedSource(name: "なんJまとめセンター", feedURL: URL(string: "https://nanj-matome-center.blog.jp/index.rdf")!),
        FeedSource(name: "なんJ PRIDE", feedURL: URL(string: "http://blog.livedoor.jp/rock1702/index.rdf")!),
        FeedSource(name: "なんJワールド", feedURL: URL(string: "https://nanjworld.blog.jp/index.rdf")!),
        FeedSource(name: "なんJゴッド", feedURL: URL(string: "https://nanjgod.blog.jp/index.rdf")!),
        FeedSource(name: "なんJクエスト", feedURL: URL(string: "https://nanjquest.blog.jp/index.rdf")!),
        FeedSource(name: "なんじぇいスタジアム", feedURL: URL(string: "http://blog.livedoor.jp/nanjstu/index.rdf")!),
        FeedSource(name: "SS速報VIPブログ", feedURL: URL(string: "http://ssvip.blog.jp/index.rdf")!),
        FeedSource(name: "まにゅそく", feedURL: URL(string: "https://manyusoku.blog.jp/index.rdf")!),
        FeedSource(name: "ゆるゆるプレイス", feedURL: URL(string: "https://yuruyuruplace.blog.jp/index.rdf")!),
        FeedSource(name: "しゅらさん", feedURL: URL(string: "https://shurasan.blog.jp/index.rdf")!),
        FeedSource(name: "ぐら速", feedURL: URL(string: "https://gurasoku.blog.jp/index.rdf")!),
        FeedSource(name: "ぁゃιぃNEWS2nd", feedURL: URL(string: "https://ayacnews2nd.com/feed")!),
        FeedSource(name: "なんでも受信遅報", feedURL: URL(string: "https://nandemojushin.blog.jp/index.rdf")!),

        // === ゲーム・アニメ ===
        FeedSource(name: "はちま起稿", feedURL: URL(string: "http://blog.esuteru.com/index.rdf")!),
        FeedSource(name: "オレ的ゲーム速報", feedURL: URL(string: "http://jin115.com/index.rdf")!),
        FeedSource(name: "げーむやかん", feedURL: URL(string: "https://gameyakan.blog.jp/index.rdf")!),
        FeedSource(name: "アニゲー速報", feedURL: URL(string: "http://anigesokuhou.blog.jp/index.rdf")!),
        FeedSource(name: "わんこーる速報", feedURL: URL(string: "http://onecall2ch.com/index.rdf")!),
        FeedSource(name: "やらおん!", feedURL: URL(string: "http://yaraon-blog.com/feed")!),
        FeedSource(name: "ああ言えばForYou", feedURL: URL(string: "http://aaieba.livedoor.biz/index.rdf")!),
        FeedSource(name: "げーすぽch", feedURL: URL(string: "https://gespo-ch.blog.jp/index.rdf")!),
        FeedSource(name: "ゲーム魔人", feedURL: URL(string: "https://gamemajin.blog.jp/index.rdf")!),
        FeedSource(name: "ゆるゲーマー遅報", feedURL: URL(string: "https://yurugamer.blog.jp/index.rdf")!),
        FeedSource(name: "SWITCH速報", feedURL: URL(string: "https://switchsoku.com/feed")!),
        FeedSource(name: "ゲーハー黙示録", feedURL: URL(string: "http://blog.livedoor.jp/gehaha/index.rdf")!),
        FeedSource(name: "ゲーム実況者速報", feedURL: URL(string: "https://gamejikkyo.blog.jp/index.rdf")!),
        FeedSource(name: "ゲームだらだら速報", feedURL: URL(string: "https://gamdaradara.blog.jp/index.rdf")!),
        FeedSource(name: "GUNDAM.LOG", feedURL: URL(string: "https://gundamlog.com/feed")!),
        FeedSource(name: "fig速", feedURL: URL(string: "http://figsoku.blog.jp/index.rdf")!),
        FeedSource(name: "超・マンガ速報", feedURL: URL(string: "https://chomanga.org/index.rdf")!),
        FeedSource(name: "漫画まとめ速報", feedURL: URL(string: "https://mangamatome.blog.jp/index.rdf")!),
        FeedSource(name: "JUMP速報", feedURL: URL(string: "https://jumpsokuhou.blog.jp/index.rdf")!),
        FeedSource(name: "最強ジャンプ放送局", feedURL: URL(string: "https://saikyoujump.blog.jp/index.rdf")!),
        FeedSource(name: "2ch東方スレ観測所", feedURL: URL(string: "http://blog.livedoor.jp/tohosure/index.rdf")!),
        FeedSource(name: "スコ速＠ネット小説まとめ", feedURL: URL(string: "http://sukosoku.blog.jp/index.rdf")!),
        FeedSource(name: "サブカル通信", feedURL: URL(string: "https://subcultureblog.blog.jp/index.rdf")!),
        FeedSource(name: "オーバージョイド！", feedURL: URL(string: "https://overjoyed-blog.blog.jp/index.rdf")!),

        // === VTuber ===
        FeedSource(name: "VTuberNews", feedURL: URL(string: "https://vtubernews.jp/feed")!),
        FeedSource(name: "ホロ速", feedURL: URL(string: "https://holosoku.blog.jp/index.rdf")!),
        FeedSource(name: "Vtuberまとめるよ～ん", feedURL: URL(string: "https://vtubermatomeru.blog.jp/index.rdf")!),

        // === IT・テクノロジー ===
        FeedSource(name: "IT速報", feedURL: URL(string: "http://blog.livedoor.jp/itsoku/index.rdf")!),
        FeedSource(name: "ガジェット2ch", feedURL: URL(string: "https://gadget2ch.com/index.rdf")!),
        FeedSource(name: "汎用型自作PCまとめ", feedURL: URL(string: "http://blog.livedoor.jp/bluejay01-review/index.rdf")!),
        FeedSource(name: "ピカ速", feedURL: URL(string: "https://pikasoku.blog.jp/index.rdf")!),

        // === 生活・文化 ===
        FeedSource(name: "ライフハックちゃんねる弐式", feedURL: URL(string: "http://lifehack2ch.livedoor.biz/index.rdf")!),
        FeedSource(name: "お料理速報", feedURL: URL(string: "http://oryouri.2chblog.jp/index.rdf")!),
        FeedSource(name: "鬼女まとめログ", feedURL: URL(string: "http://www.kijomatomelog.com/index.rdf")!),
        FeedSource(name: "育児板拾い読み", feedURL: URL(string: "http://ikuzi2ch.blog.fc2.com/?xml")!),
        FeedSource(name: "結婚・恋愛ニュースぷらす", feedURL: URL(string: "http://blog.livedoor.jp/kekkongo/index.rdf")!),
        FeedSource(name: "かぞくちゃんねる", feedURL: URL(string: "http://kazokuchannel.blog.jp/index.rdf")!),
        FeedSource(name: "おうち速報", feedURL: URL(string: "http://ouchisokuhou.blog.jp/index.rdf")!),
        FeedSource(name: "修羅場まとめ速報", feedURL: URL(string: "http://shurabamatome.blog.jp/index.rdf")!),
        FeedSource(name: "ネタめし.com", feedURL: URL(string: "https://netameshi.blog.jp/index.rdf")!),

        // === 経済・お金 ===
        FeedSource(name: "市況かぶ全力2階建", feedURL: URL(string: "https://kabumatome.doorblog.jp/index.rdf")!),
        FeedSource(name: "稼げるまとめ速報", feedURL: URL(string: "http://kasegeru.blog.jp/index.rdf")!),
        FeedSource(name: "FX2ちゃんねる", feedURL: URL(string: "http://fx2ch.com/index.rdf")!),
        FeedSource(name: "投資ちゃんねる", feedURL: URL(string: "https://toushi-ch.blog.jp/index.rdf")!),
        FeedSource(name: "守銭奴日報", feedURL: URL(string: "https://守銭奴日報.blog.jp/index.rdf")!),
        FeedSource(name: "かせまと！", feedURL: URL(string: "https://kasemato.blog.jp/index.rdf")!),

        // === スポーツ ===
        FeedSource(name: "日刊やきう速報", feedURL: URL(string: "http://blog.livedoor.jp/yakiusoku/index.rdf")!),
        FeedSource(name: "竜速", feedURL: URL(string: "http://ryusoku.com/index.rdf")!),
        FeedSource(name: "阪神タイガースちゃんねる", feedURL: URL(string: "http://hanshintigers.blog.fc2.com/?xml")!),
        FeedSource(name: "サッカーミックスジュース", feedURL: URL(string: "http://samixjuice.blog.jp/index.rdf")!),
        FeedSource(name: "サカサカ10", feedURL: URL(string: "http://sakasaka10.blog.jp/index.rdf")!),
        FeedSource(name: "ドメサカブログ", feedURL: URL(string: "http://blog.livedoor.jp/domesaka/index.rdf")!),
        FeedSource(name: "フットカルチョ", feedURL: URL(string: "https://blog.livedoor.jp/footcalcio/index.rdf")!),
        FeedSource(name: "野球猫びいき", feedURL: URL(string: "http://blog.livedoor.jp/livejupiter2/index.rdf")!),
        FeedSource(name: "ツバメ速報", feedURL: URL(string: "https://tsubamesoku.blog.jp/index.rdf")!),
        FeedSource(name: "ベイスターズNEWS", feedURL: URL(string: "https://baystars-news.blog.jp/index.rdf")!),
        FeedSource(name: "ファイターズ王国", feedURL: URL(string: "https://fighters-kingdom.blog.jp/index.rdf")!),
        FeedSource(name: "カープ情報", feedURL: URL(string: "https://carp-info.blog.jp/index.rdf")!),
        FeedSource(name: "うまろぐ", feedURL: URL(string: "https://umalog.blog.jp/index.rdf")!),
        FeedSource(name: "バスケまとめ・COM", feedURL: URL(string: "https://basket-matome.blog.jp/index.rdf")!),
        FeedSource(name: "F1情報通", feedURL: URL(string: "https://f1jouhou.blog.jp/index.rdf")!),
        FeedSource(name: "2ch名人", feedURL: URL(string: "http://i2chmeijin.blog.fc2.com/?xml")!),

        // === 芸能・エンタメ ===
        FeedSource(name: "芸能7days", feedURL: URL(string: "https://geinouseven.blog.jp/index.rdf")!),
        FeedSource(name: "坂道情報通", feedURL: URL(string: "https://sakamichi-jouhoutsuu.blog.jp/index.rdf")!),
        FeedSource(name: "ジャニーズまとめ", feedURL: URL(string: "http://johnnysmatome.blog.jp/index.rdf")!),

        // === パチンコ・ギャンブル ===
        FeedSource(name: "パチンコ・パチスロ.com", feedURL: URL(string: "https://pachinkopachislo.com/feed")!),
        FeedSource(name: "パチスロ動画本店", feedURL: URL(string: "https://pachislot-douga.blog.jp/index.rdf")!),

        // === 車・バイク ===
        FeedSource(name: "サイ速", feedURL: URL(string: "http://saisoku.blog.jp/index.rdf")!),
        FeedSource(name: "乗り物速報", feedURL: URL(string: "http://norisoku.com/index.rdf")!),
        FeedSource(name: "車速報", feedURL: URL(string: "https://carsoku.blog.jp/index.rdf")!),
        FeedSource(name: "くるまにあ速報", feedURL: URL(string: "http://car-rider.jp/index.rdf")!),
        FeedSource(name: "バイク速報", feedURL: URL(string: "http://bikesokuhou.blog.jp/index.rdf")!),
        FeedSource(name: "ゆめ痛", feedURL: URL(string: "http://blog.livedoor.jp/motersound/index.rdf")!),

        // === ミリタリー ===
        FeedSource(name: "軍事・ミリタリー速報", feedURL: URL(string: "http://blog.livedoor.jp/corez18c24-mili777/index.rdf")!),

        // === オカルト・不思議 ===
        FeedSource(name: "オカルト遅報", feedURL: URL(string: "http://okaokaokuoku.blog.jp/index.rdf")!),

        // === 海外反応 ===
        FeedSource(name: "海外の万国反応記", feedURL: URL(string: "http://www.all-nationz.com/index.rdf")!),
        FeedSource(name: "劇訳表示。", feedURL: URL(string: "http://www.gekiyaku.com/index.rdf")!),
        FeedSource(name: "パンドラの憂鬱", feedURL: URL(string: "http://kaigainohannoublog.blog55.fc2.com/?xml")!),
        FeedSource(name: "こんなニュースにでくわした", feedURL: URL(string: "http://www.konnanews.com/index.rdf")!),
        FeedSource(name: "どんぐりこ", feedURL: URL(string: "http://dng65.com/index.rdf")!),
        FeedSource(name: "海外トークログ", feedURL: URL(string: "https://kaigai-talk-log.blog.jp/index.rdf")!),
        FeedSource(name: "海外さんいらっしゃい", feedURL: URL(string: "https://kaigaisan.blog.jp/index.rdf")!),
        FeedSource(name: "楽韓Web", feedURL: URL(string: "https://rakukan.net/feed")!),

        // === 旅行・アウトドア ===
        FeedSource(name: "エアライン本舗", feedURL: URL(string: "http://airlinehonpo.blog.fc2.com/?xml")!),
        FeedSource(name: "登山ちゃんねる", feedURL: URL(string: "http://tozanchannel.blog.jp/index.rdf")!),
    ]
}
